version: '3.8'

services:
  test-db:
    image: postgres:13-alpine
    container_name: flyway-demo-test-db
    environment:
      POSTGRES_DB: flyway-demo-test-db
      POSTGRES_USER: flyway-demo-user
      POSTGRES_PASSWORD: flyway-demo-pwd
      CONFIGS: "listen_addresses:'*'"
    ports:
      - 9933:5432
